modLoader="javafml"
loaderVersion="[47,)"
#modLoader="kotlinforforge"
#loaderVersion="[4,)"

license = "MIT"
issueTrackerURL = "https://github.com/Alexnijjar/subterrestrial/issues"

[[mods]]
modId = "subterrestrial"
version = "${version}"
displayName = "Subterrestrial"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/subterrestrial"
logoFile = "icon.png"
authors = "Alex Nijjar"
description = "Adds Underground Cabins from Terraria."

[[dependencies.subterrestrial]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.subterrestrial]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"