modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"
issueTrackerURL = "https://github.com/Alexnijjar/${github_name}/issues"

[[mods]]
modId = "subterrestrial"
version = "${version}"
displayName = "Subterrestrial"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/subterrestrial"
logoFile = "icon.png"
authors = "Alex Nijjar"
credits = ""
description = "Adds Underground Cabins from Terraria."

[[dependencies.subterrestrial]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.subterrestrial]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"